version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/trifulca/buchonip
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  deploy:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/trifulca/buchonip
    steps:
      - checkout
      - run: echo -e "Host hugoruscitti.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: go get -v -t -d ./...
      - run: make deploy
workflows:
  version: 2
  compilar:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v\d+.\d+.\d+/
